<?php

/**
 * @file
 * Calypso Boost
 *
 * @author Hein Bekker <hein@netbek.co.za>
 * @copyright (c) 2015 Hein Bekker
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GPLv2
 */
module_load_include('inc', 'calypso_boost', 'includes/calypso_boost');

/**
 * Implements hook_menu_link_insert().
 */
function calypso_boost_menu_link_insert($link) {
  CalypsoBoost::expireMenuLink($link);
}

/**
 * Implements hook_menu_link_update().
 */
function calypso_boost_menu_link_update($link) {
  CalypsoBoost::expireMenuLink($link);
}

/**
 * Implements hook_menu_link_delete().
 */
function calypso_boost_menu_link_delete($link) {
  CalypsoBoost::expireMenuLink($link);
}

/**
 * Implements hook_node_insert().
 */
function calypso_boost_node_insert($node) {
  CalypsoBoost::expireNode($node);
}

/**
 * Implements hook_node_update().
 */
function calypso_boost_node_update($node) {
  CalypsoBoost::expireNode($node);
}

/**
 * Implements hook_node_delete().
 */
function calypso_boost_node_delete($node) {
  CalypsoBoost::expireNode($node);
}
